---

- name: "PREREQ | If required install libselinux package to manage file changes."
  package:
      name: libselinux-python3
      state: present
  when:
      - '"libselinux-python3" not in ansible_facts.packages'
